FROM debian:bullseye

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

# Установка systemd, SSH, Python и Ansible
RUN apt-get update && \
    apt-get install -y \
        systemd systemd-sysv \
        sudo iproute2 \
        openssh-server \
        curl gnupg2 \
        python3 python3-pip python3-apt dbus && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Установка Ansible последней версии (или минимально необходимой ≥ 2.12)
RUN pip3 install "ansible>=2.12.0"

# Настройка SSH
RUN mkdir -p /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/^#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

# Открываем порт 22
EXPOSE 22

# Указываем systemd как основной процесс
STOPSIGNAL SIGRTMIN+3
VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
