---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian
    image: custom_debian_systemd
    pre_build_image: false
    privileged: true
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      container: docker
    stop_timeout: 20
    ansible_python_interpreter: /usr/bin/python3

provisioner:
  name: ansible
  playbooks:
    converge: ../../collector.yml
  config_options:
    defaults:
      become: false
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true

verifier:
  name: ansible
