---
dependency:
  name: galaxy

driver:
  name: docker
  
platforms:
  - name: debian
    image: custom_debian_systemd  # можно любое название
    build_image: true
    dockerfile: Dockerfile
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_python_interpreter: /usr/bin/python3
    
provisioner:
  name: ansible
  playbooks:
    converge: ../../collector.yml
  config_options:
    defaults:
      become: false
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true

verifier:
  name: ansible
