---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: debian:bullseye
    privileged: true
    pre_build_image: true
  - name: rocky
    image: rockylinux/rockylinux:8
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../collector.yml
verifier:
  name: ansible
