---
- name: Prepare Debian container
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Python 3
      apt:
        name: python3
        state: present
        update_cache: yes
