name: Ansible Lint Check

on:
  push:
    branches:
      - develop

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint ansible

      - name: Run ansible-lint
        run: ansible-lint collector.yml
