name: Molecule Test

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Clean up existing Docker installations
      run: |
        sudo systemctl stop docker containerd || true
        sudo apt-get remove -y docker docker-engine docker.io containerd containerd.io || true
        sudo apt-get autoremove -y
        sudo rm -rf /var/lib/docker /etc/docker
        sudo rm -f /etc/apt/keyrings/docker.gpg
        sudo rm -f /etc/apt/sources.list.d/docker.list

    - name: Install Docker dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release

    - name: Add Docker official GPG key
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Setup Docker repository
      run: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - name: Add current user to docker group
      run: |
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Verify Docker installation
      run: |
        sudo systemctl start docker
        docker --version
        docker run hello-world

    - name: Install Molecule and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule ansible docker

    - name: Run molecule test
      run: |
        molecule test
