name: Molecule Test

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release \
          software-properties-common

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com | sudo sh
        sudo systemctl start docker
        echo "Docker version:"
        sudo docker --version

    - name: Install Molecule and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "molecule==3.6.0" "molecule-docker==1.1.0" ansible

    - name: Verify Docker
      run: |
        sudo docker run --rm hello-world

    - name: Run molecule test
      run: |
        cd molecule/default
        molecule test --all
